services:
  database:
    image: postgres:16-alpine
    container_name: nimbus-db
    environment:
      POSTGRES_USER: nimbus
      POSTGRES_PASSWORD: nimbus_password
      POSTGRES_DB: nimbus_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nimbus"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nimbus-network

  migration:
    image: migrate/migrate
    container_name: nimbus-migration
    volumes:
      - ./migrations:/migrations 
    environment:
      MIGRATE_CONN_STR: "postgres://nimbus:nimbus_password@database:5432/nimbus_db?sslmode=disable&charset=utf8mb4&parseTime=True&loc=Local"
    command: >
      /bin/sh -c '
      echo "Waiting a few seconds for the DB to be fully available..." &&
      sleep 5 &&
      migrate -path /migrations -database "$MIGRATE_CONN_STR" up
      '
    depends_on:
      database:
        condition: service_healthy
    restart: "no"

volumes:
  postgres_data:
    driver: local

networks:
  nimbus-network:
    driver: bridge
