// Code generated by MockGen. DO NOT EDIT.
// Source: internal/task_runnner/domain/repository/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/task_runnner/domain/repository/interfaces.go -destination=internal/task_runnner/domain/repository/mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "nimbus/internal/task_runnner/domain/entity"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskRunnerRepository is a mock of TaskRunnerRepository interface.
type MockTaskRunnerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRunnerRepositoryMockRecorder
	isgomock struct{}
}

// MockTaskRunnerRepositoryMockRecorder is the mock recorder for MockTaskRunnerRepository.
type MockTaskRunnerRepositoryMockRecorder struct {
	mock *MockTaskRunnerRepository
}

// NewMockTaskRunnerRepository creates a new mock instance.
func NewMockTaskRunnerRepository(ctrl *gomock.Controller) *MockTaskRunnerRepository {
	mock := &MockTaskRunnerRepository{ctrl: ctrl}
	mock.recorder = &MockTaskRunnerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRunnerRepository) EXPECT() *MockTaskRunnerRepositoryMockRecorder {
	return m.recorder
}

// AssignTask mocks base method.
func (m *MockTaskRunnerRepository) AssignTask(runnerID, taskID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignTask", runnerID, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignTask indicates an expected call of AssignTask.
func (mr *MockTaskRunnerRepositoryMockRecorder) AssignTask(runnerID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignTask", reflect.TypeOf((*MockTaskRunnerRepository)(nil).AssignTask), runnerID, taskID)
}

// GetAll mocks base method.
func (m *MockTaskRunnerRepository) GetAll() ([]entity.TaskRunner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]entity.TaskRunner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockTaskRunnerRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockTaskRunnerRepository)(nil).GetAll))
}

// GetByID mocks base method.
func (m *MockTaskRunnerRepository) GetByID(id uuid.UUID) (*entity.TaskRunner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*entity.TaskRunner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTaskRunnerRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTaskRunnerRepository)(nil).GetByID), id)
}

// GetByTaskID mocks base method.
func (m *MockTaskRunnerRepository) GetByTaskID(taskID uuid.UUID) ([]entity.TaskRunner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTaskID", taskID)
	ret0, _ := ret[0].([]entity.TaskRunner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTaskID indicates an expected call of GetByTaskID.
func (mr *MockTaskRunnerRepositoryMockRecorder) GetByTaskID(taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTaskID", reflect.TypeOf((*MockTaskRunnerRepository)(nil).GetByTaskID), taskID)
}

// Store mocks base method.
func (m *MockTaskRunnerRepository) Store(runner *entity.TaskRunner) (*entity.TaskRunner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", runner)
	ret0, _ := ret[0].(*entity.TaskRunner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Store indicates an expected call of Store.
func (mr *MockTaskRunnerRepositoryMockRecorder) Store(runner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockTaskRunnerRepository)(nil).Store), runner)
}

// UnassignTask mocks base method.
func (m *MockTaskRunnerRepository) UnassignTask(runnerID, taskID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnassignTask", runnerID, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnassignTask indicates an expected call of UnassignTask.
func (mr *MockTaskRunnerRepositoryMockRecorder) UnassignTask(runnerID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassignTask", reflect.TypeOf((*MockTaskRunnerRepository)(nil).UnassignTask), runnerID, taskID)
}
