// Code generated by MockGen. DO NOT EDIT.
// Source: internal/task_runnner/domain/service/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/task_runnner/domain/service/interfaces.go -destination=internal/task_runnner/domain/service/mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entity "nimbus/internal/task_runnner/domain/entity"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskRunnerService is a mock of TaskRunnerService interface.
type MockTaskRunnerService struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRunnerServiceMockRecorder
	isgomock struct{}
}

// MockTaskRunnerServiceMockRecorder is the mock recorder for MockTaskRunnerService.
type MockTaskRunnerServiceMockRecorder struct {
	mock *MockTaskRunnerService
}

// NewMockTaskRunnerService creates a new mock instance.
func NewMockTaskRunnerService(ctrl *gomock.Controller) *MockTaskRunnerService {
	mock := &MockTaskRunnerService{ctrl: ctrl}
	mock.recorder = &MockTaskRunnerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRunnerService) EXPECT() *MockTaskRunnerServiceMockRecorder {
	return m.recorder
}

// AssignTask mocks base method.
func (m *MockTaskRunnerService) AssignTask(runnerID, taskID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignTask", runnerID, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignTask indicates an expected call of AssignTask.
func (mr *MockTaskRunnerServiceMockRecorder) AssignTask(runnerID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignTask", reflect.TypeOf((*MockTaskRunnerService)(nil).AssignTask), runnerID, taskID)
}

// CreateRunner mocks base method.
func (m *MockTaskRunnerService) CreateRunner(runner *entity.TaskRunner) (*entity.TaskRunner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRunner", runner)
	ret0, _ := ret[0].(*entity.TaskRunner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRunner indicates an expected call of CreateRunner.
func (mr *MockTaskRunnerServiceMockRecorder) CreateRunner(runner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRunner", reflect.TypeOf((*MockTaskRunnerService)(nil).CreateRunner), runner)
}

// GetRunner mocks base method.
func (m *MockTaskRunnerService) GetRunner(id uuid.UUID) (*entity.TaskRunner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRunner", id)
	ret0, _ := ret[0].(*entity.TaskRunner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRunner indicates an expected call of GetRunner.
func (mr *MockTaskRunnerServiceMockRecorder) GetRunner(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRunner", reflect.TypeOf((*MockTaskRunnerService)(nil).GetRunner), id)
}

// GetRunners mocks base method.
func (m *MockTaskRunnerService) GetRunners() ([]entity.TaskRunner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRunners")
	ret0, _ := ret[0].([]entity.TaskRunner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRunners indicates an expected call of GetRunners.
func (mr *MockTaskRunnerServiceMockRecorder) GetRunners() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRunners", reflect.TypeOf((*MockTaskRunnerService)(nil).GetRunners))
}

// GetRunnersByTaskID mocks base method.
func (m *MockTaskRunnerService) GetRunnersByTaskID(taskID uuid.UUID) ([]entity.TaskRunner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRunnersByTaskID", taskID)
	ret0, _ := ret[0].([]entity.TaskRunner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRunnersByTaskID indicates an expected call of GetRunnersByTaskID.
func (mr *MockTaskRunnerServiceMockRecorder) GetRunnersByTaskID(taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRunnersByTaskID", reflect.TypeOf((*MockTaskRunnerService)(nil).GetRunnersByTaskID), taskID)
}

// UnassignTask mocks base method.
func (m *MockTaskRunnerService) UnassignTask(runnerID, taskID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnassignTask", runnerID, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnassignTask indicates an expected call of UnassignTask.
func (mr *MockTaskRunnerServiceMockRecorder) UnassignTask(runnerID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassignTask", reflect.TypeOf((*MockTaskRunnerService)(nil).UnassignTask), runnerID, taskID)
}

// MockDispatchService is a mock of DispatchService interface.
type MockDispatchService struct {
	ctrl     *gomock.Controller
	recorder *MockDispatchServiceMockRecorder
	isgomock struct{}
}

// MockDispatchServiceMockRecorder is the mock recorder for MockDispatchService.
type MockDispatchServiceMockRecorder struct {
	mock *MockDispatchService
}

// NewMockDispatchService creates a new mock instance.
func NewMockDispatchService(ctrl *gomock.Controller) *MockDispatchService {
	mock := &MockDispatchService{ctrl: ctrl}
	mock.recorder = &MockDispatchServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDispatchService) EXPECT() *MockDispatchServiceMockRecorder {
	return m.recorder
}

// DispatchTask mocks base method.
func (m *MockDispatchService) DispatchTask(ctx context.Context, taskID uuid.UUID, payload string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DispatchTask", ctx, taskID, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// DispatchTask indicates an expected call of DispatchTask.
func (mr *MockDispatchServiceMockRecorder) DispatchTask(ctx, taskID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DispatchTask", reflect.TypeOf((*MockDispatchService)(nil).DispatchTask), ctx, taskID, payload)
}
