// Code generated by MockGen. DO NOT EDIT.
// Source: internal/workflow/domain/repository/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/workflow/domain/repository/interfaces.go -destination=internal/workflow/domain/repository/mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "nimbus/internal/workflow/domain/entity"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskRepository is a mock of TaskRepository interface.
type MockTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepositoryMockRecorder
	isgomock struct{}
}

// MockTaskRepositoryMockRecorder is the mock recorder for MockTaskRepository.
type MockTaskRepositoryMockRecorder struct {
	mock *MockTaskRepository
}

// NewMockTaskRepository creates a new mock instance.
func NewMockTaskRepository(ctrl *gomock.Controller) *MockTaskRepository {
	mock := &MockTaskRepository{ctrl: ctrl}
	mock.recorder = &MockTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepository) EXPECT() *MockTaskRepositoryMockRecorder {
	return m.recorder
}

// GetTask mocks base method.
func (m *MockTaskRepository) GetTask(id uuid.UUID) *entity.Task {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", id)
	ret0, _ := ret[0].(*entity.Task)
	return ret0
}

// GetTask indicates an expected call of GetTask.
func (mr *MockTaskRepositoryMockRecorder) GetTask(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockTaskRepository)(nil).GetTask), id)
}

// GetTasks mocks base method.
func (m *MockTaskRepository) GetTasks() []entity.Task {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasks")
	ret0, _ := ret[0].([]entity.Task)
	return ret0
}

// GetTasks indicates an expected call of GetTasks.
func (mr *MockTaskRepositoryMockRecorder) GetTasks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasks", reflect.TypeOf((*MockTaskRepository)(nil).GetTasks))
}

// StoreTask mocks base method.
func (m *MockTaskRepository) StoreTask(task *entity.Task) (*entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreTask", task)
	ret0, _ := ret[0].(*entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreTask indicates an expected call of StoreTask.
func (mr *MockTaskRepositoryMockRecorder) StoreTask(task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreTask", reflect.TypeOf((*MockTaskRepository)(nil).StoreTask), task)
}

// UpdateTask mocks base method.
func (m *MockTaskRepository) UpdateTask(task *entity.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", task)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockTaskRepositoryMockRecorder) UpdateTask(task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockTaskRepository)(nil).UpdateTask), task)
}

// UpdateTaskStatus mocks base method.
func (m *MockTaskRepository) UpdateTaskStatus(id uuid.UUID, fromStatus, toStatus entity.TaskStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStatus", id, fromStatus, toStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskStatus indicates an expected call of UpdateTaskStatus.
func (mr *MockTaskRepositoryMockRecorder) UpdateTaskStatus(id, fromStatus, toStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStatus", reflect.TypeOf((*MockTaskRepository)(nil).UpdateTaskStatus), id, fromStatus, toStatus)
}

// MockWorkflowRepository is a mock of WorkflowRepository interface.
type MockWorkflowRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowRepositoryMockRecorder
	isgomock struct{}
}

// MockWorkflowRepositoryMockRecorder is the mock recorder for MockWorkflowRepository.
type MockWorkflowRepositoryMockRecorder struct {
	mock *MockWorkflowRepository
}

// NewMockWorkflowRepository creates a new mock instance.
func NewMockWorkflowRepository(ctrl *gomock.Controller) *MockWorkflowRepository {
	mock := &MockWorkflowRepository{ctrl: ctrl}
	mock.recorder = &MockWorkflowRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowRepository) EXPECT() *MockWorkflowRepositoryMockRecorder {
	return m.recorder
}

// GetWorkflow mocks base method.
func (m *MockWorkflowRepository) GetWorkflow(id uuid.UUID) *entity.Workflow {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflow", id)
	ret0, _ := ret[0].(*entity.Workflow)
	return ret0
}

// GetWorkflow indicates an expected call of GetWorkflow.
func (mr *MockWorkflowRepositoryMockRecorder) GetWorkflow(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflow", reflect.TypeOf((*MockWorkflowRepository)(nil).GetWorkflow), id)
}

// GetWorkflows mocks base method.
func (m *MockWorkflowRepository) GetWorkflows() []entity.Workflow {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflows")
	ret0, _ := ret[0].([]entity.Workflow)
	return ret0
}

// GetWorkflows indicates an expected call of GetWorkflows.
func (mr *MockWorkflowRepositoryMockRecorder) GetWorkflows() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflows", reflect.TypeOf((*MockWorkflowRepository)(nil).GetWorkflows))
}

// StoreWorkflow mocks base method.
func (m *MockWorkflowRepository) StoreWorkflow(workflow *entity.Workflow) (*entity.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreWorkflow", workflow)
	ret0, _ := ret[0].(*entity.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreWorkflow indicates an expected call of StoreWorkflow.
func (mr *MockWorkflowRepositoryMockRecorder) StoreWorkflow(workflow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreWorkflow", reflect.TypeOf((*MockWorkflowRepository)(nil).StoreWorkflow), workflow)
}

// UpdateWorkflow mocks base method.
func (m *MockWorkflowRepository) UpdateWorkflow(workflow *entity.Workflow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkflow", workflow)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWorkflow indicates an expected call of UpdateWorkflow.
func (mr *MockWorkflowRepositoryMockRecorder) UpdateWorkflow(workflow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkflow", reflect.TypeOf((*MockWorkflowRepository)(nil).UpdateWorkflow), workflow)
}
